/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Hashtable;
import java.util.concurrent.atomic.AtomicInteger;

public class App {
  
    public static void main(String[] args) {

        Hashtable<Integer, Cliente> clientes = new Hashtable<>();
        AtomicInteger contador = new AtomicInteger();
        Thread prompt = new Thread(new PromptComandos(clientes));

        System.out.println("\u2591\u2592\u2592 Iniciando Servidor \u2591\u2592\u2592");
        int porta = 1234;

        try (ServerSocket servidor = new ServerSocket(porta)) {
            prompt.start();
            while (true) {
                Socket cliente = servidor.accept();
                Integer id = contador.incrementAndGet();

                // Estabelecimento dos fluxos de entrada
                BufferedReader entrada = new BufferedReader(new InputStreamReader(cliente.getInputStream(), "UTF-8"));
                DataOutputStream saida = new DataOutputStream(cliente.getOutputStream());
            
                clientes.put(id, new Cliente(cliente, entrada, saida));
            }

        }catch (IOException e){
            System.err.println("Erro ao iniciar servidor: " + e.getMessage());
        }


    }
}
