/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;

public class App {

    public static void main(String[] args){

        System.out.println("...:: Iniciando Cliente ::..");

        String ipServidor = "localhost";
        int portaServidor = 1234;

        try (Socket conexao = new Socket(ipServidor, portaServidor)) {

            System.out.println("Conectando Servidor: ");

            // Estabelecimento dos fluxos de entrada
            BufferedReader entrada = new BufferedReader(new InputStreamReader(conexao.getInputStream(), "UTF-8"));

            DataOutputStream saida = new DataOutputStream(conexao.getOutputStream());

        
           // Comunicação
            String recebido;
          
            do {
                recebido = entrada.readLine();
                System.out.println("Servidor falou: " + recebido);
            }while (!recebido.equals("sair"));
            

        } catch (Exception e) {
            System.out.println("erro ao conectar: " + e.getMessage());
        }

        

    }
}