/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.Scanner;

public class App {

    public static void main(String[] args){

        System.out.println("...:: Iniciando Cliente ::..");

        String ipServidor = "localhost";
        int portaServidor = 1234;

        try (Socket conexao = new Socket(ipServidor, portaServidor)) {

            System.out.println("Conectando Servidor: ");

            // Estabelecimento dos fluxos de entrada
            BufferedReader entrada = new BufferedReader(new InputStreamReader(conexao.getInputStream(), "UTF-8"));

            DataOutputStream saida = new DataOutputStream(conexao.getOutputStream());

            // Comnunicação
            // saida.writeBytes("Oi, sou o cliente\n");
            // saida.flush();
            // String recebido = entrada.readLine();
            // System.out.println("servidor falou: "+ recebido);

           // Comunicação
            String recebido;
            Scanner teclado = new Scanner(System.in);
            String mensagem;


            do {
                System.out.println(">");
                mensagem = teclado.nextLine();
                saida.writeBytes(mensagem + "\n");
                saida.flush();
                recebido = entrada.readLine();
                System.out.println("Servidor falou: " + recebido);
                System.out.println("Cliente falou: " + mensagem);
            }while (!mensagem.equals("sair"));
            
            teclado.close();

        } catch (Exception e) {
            System.out.println("erro ao conectar: " + e.getMessage());
        }

        

    }
}
