/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo;

import java.awt.*;


public class App {


    public static void main(String[] args) throws Exception {

        Segmentos seg = new Segmentos();


    }
}
